/** Auto-generated from our SEO content build (blog). */
export type BlogPost = {
  slug: string;
  category: string;
  title: string;
  metaDescription: string;
  teaser: string;
  bodyHtml: string;
};

export const posts: BlogPost[] = [
  {
    slug: "virginia-state-inspection-guide",
    category: "Inspections",
    title: "Virginia State Inspection: What Arlington Drivers Need to Know",
    metaDescription: "A plain-English guide to the Virginia state safety inspection for Arlington drivers, what's checked, what fails, and how to pass the first time.",
    teaser: "What the inspector actually checks, why cars fail, and how to read your sticker so you're never caught driving on an expired one.",
    bodyHtml: "<p>Every vehicle registered in Virginia needs a valid safety-inspection sticker, and if you live in Arlington, that's a yearly ritual. Here's what the inspection actually involves, why cars fail, and how to walk out with a passing sticker the first time.</p>\n<h2>What the inspection checks</h2>\n<p>A certified inspector runs the Virginia State Police checklist, focused entirely on whether the car is safe to drive: brakes (pads, rotors, lines, parking brake), steering and suspension (ball joints, tie rods, play in the wheel), tires (tread depth and condition), all exterior lights, wipers and washer, horn, mirrors, windshield, seat belts, the fuel system, and exhaust security.</p>\n<h2>The most common reasons cars fail</h2>\n<ul>\n<li><strong>Worn brakes</strong>, thin pads or scored rotors. Catch these early with a <a href=\"/services/brake-repair\">free brake inspection</a>.</li>\n<li><strong>Tires</strong>, tread below 2/32\", or sidewall damage.</li>\n<li><strong>Lights</strong>, a single burned-out bulb will fail you (and it's a cheap fix).</li>\n<li><strong>Steering/suspension play</strong>, loose tie rods or ball joints. See <a href=\"/services/suspension-steering\">suspension &amp; steering</a>.</li>\n<li><strong>Wipers and windshield</strong>, torn blades or a crack in the driver's view.</li>\n</ul>\n<h2>How to read your sticker</h2>\n<p>The number in the center of the sticker is the month it expires; the surrounding numbers show the year. Your inspection is due by the <em>end</em> of that month. Driving on an expired sticker is a ticketable offense across Northern Virginia, so don't let it slide.</p>\n<h2>Passing the first time</h2>\n<p>If you already suspect a problem, a squeal from the brakes, a wiper that streaks, a light that's out, fix it before inspection day or choose a shop that can do both at once. At TAB Motors, if something fails we show you the part, quote it upfront, and can usually repair it the same day so you leave with a sticker instead of a rejection. Call (703) 243-3080.</p>",
  },
  {
    slug: "virginia-emissions-test-explained",
    category: "Inspections",
    title: "The Virginia Emissions Test, Explained (Arlington & Fairfax County)",
    metaDescription: "How the Northern Virginia emissions test works, why cars fail, and how to pass, for drivers in Arlington, Fairfax and the DC suburbs.",
    teaser: "Why Northern Virginia has an emissions test, what 'not ready' means, and the number-one reason cars fail (hint: it's that dashboard light).",
    bodyHtml: "<p>If you live in Arlington, Fairfax, Alexandria or most of the inner DC suburbs, your car needs an emissions test every two years to renew its registration. It's separate from the safety inspection, and it trips up a lot of people. Here's how it works.</p>\n<h2>Why Northern Virginia has emissions testing</h2>\n<p>The inner suburbs are part of a federally designated air-quality region, so the Commonwealth requires periodic emissions testing to keep older, dirtier vehicles in check. Most gas vehicles from 1996 and newer are included; brand-new cars (roughly their first four model years) are typically exempt.</p>\n<h2>How the test works</h2>\n<p>For 1996-and-newer vehicles, it's an <strong>OBD test</strong>: a technician plugs into your car's computer and confirms the emissions systems are functioning, that there are no active fault codes, and that the \"readiness monitors\" have completed their self-checks.</p>\n<h2>Why cars fail, and \"not ready\"</h2>\n<p>The number-one failure is a <strong>check engine light</strong>. An illuminated light is an automatic fail, full stop. The second most common issue is a <strong>\"not ready\"</strong> status, usually because the battery was recently disconnected or the car's computer was reset, so the monitors haven't finished. The fix for \"not ready\" is simply to drive the car through a normal mix of city and highway driving for a few days so the monitors complete.</p>\n<h2>The usual culprits behind a check engine light</h2>\n<ul>\n<li>Failing oxygen (O2) sensor</li>\n<li>A loose or bad gas cap (an easy EVAP fix)</li>\n<li>Catalytic converter below efficiency</li>\n<li>Engine misfire from worn plugs or coils</li>\n</ul>\n<p>The advantage of testing at a full-service shop is simple: if your car fails, we <a href=\"/services/engine-diagnostics\">diagnose the cause</a>, repair it, and re-test, all in one place. Call TAB Motors at (703) 243-3080.</p>",
  },
  {
    slug: "how-often-oil-change",
    category: "Maintenance",
    title: "How Often Should You Really Change Your Oil?",
    metaDescription: "The truth about oil-change intervals for modern cars, synthetic vs conventional, city driving, and why the old '3,000 miles' rule is mostly gone.",
    teaser: "The '3,000-mile' rule is mostly a myth now, but severe city driving changes the math. Here's how to find your real interval.",
    bodyHtml: "<p>Ask five people how often to change your oil and you'll get five answers. The honest one is: it depends on your oil, your engine, and how you drive. Here's how to figure out your real interval.</p>\n<h2>Synthetic vs. conventional</h2>\n<p>Full synthetic oil is more stable and lasts longer, most modern engines running it can go 5,000 to 7,500 miles between changes, and some manufacturers spec even longer. Conventional oil breaks down faster and is closer to a 3,000–5,000 mile interval. Many newer engines <em>require</em> synthetic, especially turbocharged ones, so the choice may already be made for you.</p>\n<h2>The old 3,000-mile rule</h2>\n<p>That rule dates from the era of conventional oil and simpler engines. With today's synthetics it's usually overkill, but the quick-lube industry loves it. We won't tell you to come in twice as often as you need to.</p>\n<h2>Why DC-area driving is \"severe\"</h2>\n<p>Here's the catch: your owner's manual has a \"severe service\" schedule, and a lot of Arlington driving qualifies. Short trips that never fully warm the engine, stop-and-go traffic on 66 and 395, extended idling, and hot humid summers all shorten oil life. If that's your commute, lean toward the shorter end of the interval.</p>\n<h2>Signs you're overdue</h2>\n<ul>\n<li>Oil-life monitor at or near 0%</li>\n<li>Oil on the dipstick looks black and gritty</li>\n<li>A faint ticking on cold start-up</li>\n<li>It's simply been too long or too many miles</li>\n</ul>\n<p>The simplest approach: change it on your manufacturer's schedule with the right oil, and let us log your mileage so the next one's on time. An <a href=\"/services/oil-change\">oil change</a> is cheap; an engine isn't. Call TAB Motors at (703) 243-3080.</p>",
  },
  {
    slug: "brake-warning-signs",
    category: "Brakes",
    title: "6 Signs Your Brakes Need Attention Now",
    metaDescription: "Squealing, grinding, a soft pedal or a pull to one side, the warning signs your brakes need service before it becomes a safety issue or a bigger bill.",
    teaser: "Squeal, grind, shimmy, soft pedal, six things your brakes do to warn you, and which one means 'stop driving and call now.'",
    bodyHtml: "<p>Brakes rarely fail without warning, they tell you they're wearing out, if you know what to listen and feel for. Catch these six signs early and you'll usually save the rotors (and money). Ignore them and a simple pad job becomes a much bigger repair.</p>\n<h2>1. A high-pitched squeal</h2>\n<p>That intermittent squeak when you brake is often a built-in wear indicator telling you the pads are getting thin. It's the cheapest possible time to act.</p>\n<h2>2. Grinding</h2>\n<p>A metallic grinding sound means the pads are gone and metal is now cutting into the rotor. This is the \"you waited too long\" sound, it turns a pad replacement into pads <em>and</em> rotors. Get it in right away.</p>\n<h2>3. A soft or sinking pedal</h2>\n<p>If the brake pedal feels spongy or slowly sinks to the floor, you may have air in the lines, a fluid leak, or a failing master cylinder. This one affects your ability to stop, don't put it off.</p>\n<h2>4. Pulsing or vibration when braking</h2>\n<p>A steering wheel that shakes or a pedal that pulses under braking usually means warped rotors. It gets worse over time and hurts stopping distance.</p>\n<h2>5. Pulling to one side</h2>\n<p>If the car veers when you brake, one side may be worn or a caliper may be sticking. It's both a brake problem and a handling problem.</p>\n<h2>6. A brake warning light or burning smell</h2>\n<p>A dash warning light or a sharp burning odor after braking hard means stop and get it checked. A dragging brake can overheat and fail.</p>\n<p>At TAB Motors the <a href=\"/services/brake-repair\">brake inspection is free</a>, we'll show you the actual pad thickness and rotor condition and quote any work upfront. Worn brakes also fail <a href=\"/services/virginia-state-inspection\">Virginia inspection</a>, so we can handle both. Call (703) 243-3080.</p>",
  },
  {
    slug: "check-engine-light-meaning",
    category: "Diagnostics",
    title: "Check Engine Light On? Here's What It Actually Means",
    metaDescription: "What triggers a check engine light, when it's an emergency, and why reading a code is not the same as diagnosing the problem.",
    teaser: "Steady vs. flashing, the gas-cap myth that's actually true, and why a $20 code reader can't tell you what's really wrong.",
    bodyHtml: "<p>Few dashboard lights cause as much anxiety as the check engine light. The good news: it's often something minor. The important news: a few situations mean you should act now. Here's how to tell the difference.</p>\n<h2>Steady vs. flashing</h2>\n<p>A <strong>steady</strong> light means the car detected an issue you should get checked soon, but you can usually keep driving carefully. A <strong>flashing</strong> light is serious, it signals an active misfire that can dump raw fuel into and destroy your catalytic converter. If it's flashing, ease off the throttle and get to a shop; don't keep driving hard.</p>\n<h2>The gas-cap thing is real</h2>\n<p>One of the most common (and cheapest) triggers really is a loose, damaged, or missing gas cap, it creates an evaporative-system leak the car detects. Tighten it; if the light doesn't clear after a few drives, it's something else.</p>\n<h2>Why a code isn't a diagnosis</h2>\n<p>A parts-store scanner reads a trouble code like \"P0420,\" but that code points to a <em>symptom</em>, not a definitive part. P0420 might be a catalytic converter, or an upstream oxygen sensor, or an exhaust leak. Replacing the converter on a guess is how people waste hundreds of dollars. Proper <a href=\"/services/engine-diagnostics\">diagnosis</a> tests to find the actual cause.</p>\n<h2>Common causes</h2>\n<ul>\n<li>Oxygen or air-fuel sensor</li>\n<li>Loose gas cap / EVAP leak</li>\n<li>Misfire (spark plugs, coils)</li>\n<li>Catalytic converter</li>\n<li>Mass airflow sensor or vacuum leak</li>\n</ul>\n<p>And remember: a lit check engine light is an automatic <a href=\"/services/virginia-emissions-inspection\">emissions</a> failure, so it's worth sorting before renewal time. TAB Motors diagnoses it right the first time, call (703) 243-3080.</p>",
  },
  {
    slug: "car-battery-life-virginia",
    category: "Batteries",
    title: "Why Car Batteries Die Early in Virginia's Weather",
    metaDescription: "Heat, cold, and short trips all shorten car battery life in the DC area. How long batteries really last here and the warning signs to catch first.",
    teaser: "It's not the cold that kills your battery, it's the summer heat setting up the winter failure. Here's the real story.",
    bodyHtml: "<p>Car batteries in the DC area rarely last as long as people expect. Between muggy summers and cold snaps, three to four years is a typical lifespan here, and the failure almost always comes at the worst moment. Here's why, and how to see it coming.</p>\n<h2>Heat does the damage; cold reveals it</h2>\n<p>Most people blame winter, but it's summer heat that actually wears a battery out, high temperatures accelerate the internal chemistry and evaporate the electrolyte. Then the first cold morning comes along, thickening the oil and raising the power needed to crank, and the already-weakened battery finally can't do it. So the battery \"dies in winter,\" but it was really cooked in July.</p>\n<h2>Warning signs</h2>\n<ul>\n<li>Slow, labored cranking when you start the car</li>\n<li>Dashboard lights dimming, or electronics acting up</li>\n<li>You've needed a jump-start recently</li>\n<li>The battery is more than three years old</li>\n<li>A battery or charging warning light</li>\n</ul>\n<h2>It might not be the battery</h2>\n<p>A battery that keeps dying can actually be a failing <strong>alternator</strong> not charging it, or a <strong>parasitic drain</strong> pulling power while parked. That's why a proper test checks the whole <a href=\"/services/battery-alternator-starter\">charging system</a>, not just the battery, so you fix the real problem once.</p>\n<h2>Get ahead of it</h2>\n<p>A battery test takes minutes and is free at TAB Motors. If yours is on the older side or cranking slowly, have it checked before it strands you in a parking lot. Call (703) 243-3080.</p>",
  },
  {
    slug: "tpms-tire-pressure-light",
    category: "Tires",
    title: "That Tire-Pressure Light: TPMS, Explained",
    metaDescription: "What the TPMS tire-pressure light means, why it comes on in cold weather, and when it signals a leak or a failing sensor.",
    teaser: "Why the light loves cold mornings, when it means a real leak, and why 'just add air' sometimes isn't enough.",
    bodyHtml: "<p>The little horseshoe-shaped light with an exclamation point is your Tire Pressure Monitoring System (TPMS), and it confuses a lot of drivers. Here's what it's actually telling you.</p>\n<h2>Why it loves cold mornings</h2>\n<p>Air contracts as it cools, so a cold snap can drop your tire pressure enough to trip the light, even with no leak. Tire pressure falls roughly 1 PSI for every 10°F drop, which is why the light so often appears on the first cold morning of the season. Topping the tires back up to the correct pressure usually clears it.</p>\n<h2>When it means a real problem</h2>\n<p>If the light keeps coming back after you've properly inflated the tires, you likely have a <strong>slow leak</strong>, a nail, a bad valve stem, or a wheel that isn't sealing. And if the light <em>flashes</em> for a bit before staying on, that often points to a <strong>failing TPMS sensor</strong> (the sensors have small batteries that eventually die, usually after several years).</p>\n<h2>Why correct pressure matters</h2>\n<ul>\n<li>Underinflated tires wear out faster and unevenly</li>\n<li>They hurt fuel economy</li>\n<li>They can overheat at highway speed, a blowout risk</li>\n<li>Correct pressure gives you the best grip and braking</li>\n</ul>\n<h2>Don't just ignore it</h2>\n<p>Taping over the light isn't a fix. At TAB Motors we <a href=\"/services/tire-wheel-service\">diagnose the TPMS</a>, find any leak, set your pressures to spec, and service sensors when needed, so the light goes off and stays off. Call (703) 243-3080.</p>",
  },
  {
    slug: "timing-belt-vs-chain",
    category: "Maintenance",
    title: "Timing Belt vs. Timing Chain: When to Replace",
    metaDescription: "Does your car have a timing belt or a chain, and when does it need service? Why a snapped belt can total an engine, and how to avoid it.",
    teaser: "One is a scheduled replacement you must not skip; the other lasts far longer. Getting it wrong can cost you an engine.",
    bodyHtml: "<p>Buried inside your engine is one of two things keeping everything in sync: a timing <strong>belt</strong> or a timing <strong>chain</strong>. Which one you have changes your maintenance completely, and getting it wrong can mean a totaled engine.</p>\n<h2>The key difference</h2>\n<p>A timing <strong>belt</strong> is made of reinforced rubber and <em>must</em> be replaced on a schedule, commonly every 60,000 to 100,000 miles depending on the vehicle. A timing <strong>chain</strong> is metal, runs in oil, and is designed to last far longer, often the life of the engine, though it's not entirely maintenance-free.</p>\n<h2>Why a broken belt is a disaster</h2>\n<p>Most modern engines are \"interference\" designs, meaning the valves and pistons share the same space at different moments. If the timing belt snaps, that timing is lost, pistons slam into open valves, bending them and sometimes damaging more. The result is a repair that can cost several times what a scheduled belt replacement would have. That's why the interval is not a suggestion.</p>\n<h2>Replace the water pump too</h2>\n<p>On many engines the water pump is driven by the timing belt and sits right behind it. Since the labor to get in there is the expensive part, replacing the water pump, tensioner, and idlers at the same time as the belt is the smart, economical move.</p>\n<h2>Not sure which you have?</h2>\n<p>Tell us your year, make and model and we'll tell you exactly, and we won't sell you a belt job on a chain-driven engine. If you're near the interval or bought the car used with no records, get it checked. See our <a href=\"/services/timing-belt-ignition\">timing belt &amp; ignition</a> service, or call (703) 243-3080.</p>",
  },
];

export function getPost(slug: string): BlogPost | undefined {
  return posts.find((p) => p.slug === slug);
}

export function otherPosts(slug: string, limit = 3): BlogPost[] {
  return posts.filter((p) => p.slug !== slug).slice(0, limit);
}
